### ISSUE TITLE
Calculation speed

### ISSUE THREAD

**Issue by andr1976** [rheia-framework/RHEIA#12]
@DCoppitters, can you share any expected run times (ball-park) for the included examples ? I am struggling a little with what seems to be quite slow optimisation, since I have the impression that the models should not be that expensive to evaluate.

**Comment by DCoppitters** [comment]
@andr1976, My apologies for not getting back to you sooner.

One run of the example cases (H2_FUEL, H2_POWER, and H2_MOBILITY) takes a handful of seconds, mainly due to the hourly resolution considered during 1 year. 

Considering no parallelization of the jobs (i.e., the slowest scenario with 'n jobs': 1), the deterministic optimization mentioned in the tutorial (section 4.1.) should take roughly 2 hours, as the computational budget is set at 2000 runs. Of course, this time can be divided by the number of parallel jobs considered, as the model evaluations are the bottleneck. Screening the design space at polynomial order 1 (section 4.2.) should take half an hour (20 designs, with for each design, 26 sample evaluations to quantify the statistical moments on the performance indicator). Finally, the robust design optimization (section 4.3) should take around 3 days without parallelization (computational budget of 72000 model evaluations). The FOUR_BAR_TRUSS example should run almost instantaneously.
